// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqjeawbtvgnqcfbnofmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxamVhd2J0dmducWNmYm5vZm1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTUyMTUsImV4cCI6MjA1OTUzMTIxNX0.K31MFaFnqGYtec8KJAHE3lkHxmSyivFDyK-hP8xJfPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);